version: '3.8'

services:
  mysql:
    image: flightdb
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: reservation
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
        - flight-app-network
    ports:
      - "3307:3306"

  springboot-app:
    image: flight_image
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/reservation
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@123
    depends_on: 
        - mysql
    networks:
        - flight-app-network
    ports:
      - "8080:8080"
  visualizer:
    image: dockersamples/visualizer:latest
    networks:
      - flight-app-network
    ports:
      - "9091:8080"
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
networks:
  flight-app-network:
    driver: overlay
